In [1]:
import pandas as pd
import folium
from geopy import ArcGIS, distance


class Airports():

    """From an Address and radius (default 40km) creates Object containing 
    coordinates of Address, specified radius around address in kms,
    and database with info on all airports within that radius"""

    def __init__(self, location, radius=40):
        if pd.DataFrame([[location]])[0].apply(ArcGIS().geocode)[0] != None:
            airport_database = pd.read_csv("airports.csv", header=None, usecols=[0,1,2,3,4,5,6,7])
            airport_database.columns = ["ID", "Airport", "City", "Country","IATA","ICAO", "Latitude", "Longitude"]
            airport_database["Coordinates"] = airport_database.apply(lambda x: (x["Latitude"],x["Longitude"]), axis=1)

            #self.location is the tuple (lon,lat)
            self.location = pd.DataFrame([[location]])[0].apply(ArcGIS().geocode)[0].point[0:2]
            self.radius = radius
            airport_database["<xks"] = airport_database.apply(lambda x: within_x_kms(x["Coordinates"], self.location, radius), axis=1)
            self.database = airport_database[airport_database["<xks"]]
        
        else:
            self.location = None
            self.radius = None
            self.database = None
        
def within_x_kms(p1,p2, x):
    return distance.distance(p1,p2) < x

In [22]:
import pandas as pd

class Routes():

    """From two Airports objects, creates a dataframe of all routes between
       all airports in that Airports object, also keeps the departure and 
       arrival locations as elements"""

    def __init__(self, departure_Airports, arrival_Airports):
        routes_dataframe = pd.read_csv("routes.csv")
        
        self.dLocation = departure_Airports.location
        self.aLocation = arrival_Airports.location

        routes_dataframe["Source airport ID"] = routes_dataframe["Source airport ID"].apply(lambda x: convert_to_int(x))
        routes_dataframe["Destination airport ID"] = routes_dataframe["Destination airport ID"].apply(lambda x: convert_to_int(x))

        routes_dataframe.loc[:,"Flyout"] = routes_dataframe["Source airport ID"].isin(departure_Airports.database["ID"])
        helpdataframe = routes_dataframe[routes_dataframe["Flyout"]]
        
        helpdataframe.loc[:,"Flyin"] = helpdataframe["Destination airport ID"].isin(arrival_Airports.database["ID"])
        self.routedataframe = helpdataframe[helpdataframe["Flyin"]]

        self.routedataframe.loc[:,"Departure Coordinates"] = self.routedataframe["Source airport ID"].apply(lambda x: extract_route_coordinates(departure_Airports.database, x))

        self.routedataframe.loc[:,"Arrival Coordinates"] = self.routedataframe["Destination airport ID"].apply(lambda x: extract_route_coordinates(arrival_Airports.database, x))
        
#To convert aiport ID to ints
def convert_to_int(x):
    if x!=r"\N":
        return int(x)
    else:
        return 0

#To help extract coordinates of airport to copy to relevant route
#This isolates the correct airport's coordinates
def extract_route_coordinates(airports, AirportID):
    airport = airports[airports["ID"] == AirportID]
    return airport.iloc[-1,-2]

dAirports = Airports("Toronto", 40)
aAirports = Airports("Munich", 40)

Routes(dAirports, aAirports).routedataframe

,Airline,Airline ID,Source airport,Source airport ID,Destination airport,Destination airport ID,Codeshare,Stops,Equipment,Flyout,Flyin,Departure Coordinates,Arrival Coordinates
8446,AC,330,YYZ,193,MUC,346,NaN,0,77W,True,True,"(43.6772003174, -79.63059997559999)","(48.353802, 11.7861)"
38866,LH,3320,YYZ,193,MUC,346,Y,0,77W,True,True,"(43.6772003174, -79.63059997559999)","(48.353802, 11.7861)"

In [8]:
import pandas as pd
import folium
from geopy import ArcGIS, distance
from airport_search import Airports
from routes import Routes
import math

class AirportMap():
    
    """Takes one or two Airport objects, Creates a folium map that, 
        if one Airport object is entered, maps the airports within 
        the Airport Object's radius and, 
        if two Airport objects are entered, maps both Airport Objects 
        and the routes between them in Great Circles"""

    def __init__(self, departure_Airports, arrival_Airports=None):
        
        figure = folium.Figure(width=1000,height=500)
        
        #!!!Add in Routes!!!
        if arrival_Airports != None and arrival_Airports.location != None and departure_Airports != None and departure_Airports.location != None:

            self.allAirportsDataframe = departure_Airports.database.append(arrival_Airports.database)

            #midpoint between longs and lats of the two Airport.locations
            #used to center the map
            self.midpoint = (round(((departure_Airports.location[0]+arrival_Airports.location[0])/2), 5), round(((departure_Airports.location[1]+arrival_Airports.location[1])/2),5))
            
            distance1 = distance.distance(departure_Airports.location, arrival_Airports.location) 
            zoom = calc_zoom(distance1)

            mappy = folium.Map(location = self.midpoint, tiles="Stamen Terrain", 
                            zoom_start=zoom, min_zoom=2).add_to(figure)

            fga = folium.FeatureGroup(name="Airports")
            location = folium.FeatureGroup(name="Your Location")

            for latitude, longitude, name, city, country in zip(self.allAirportsDataframe["Latitude"],self.allAirportsDataframe["Longitude"],self.allAirportsDataframe["Airport"],
                                                                self.allAirportsDataframe["City"],self.allAirportsDataframe["Country"]):

                if isinstance(city, float):
                    city = "None"
                else:
                    pass

                if isinstance(name, float):
                    city = "None"
                else:
                    pass

                if isinstance(country, float):
                    city = "None"
                else:
                    pass

                tooltip1 = "Airport: "+ name + "  City: " + city + "  Country: " + country

                fga.add_child(folium.CircleMarker(location=[latitude,longitude], radius=4,
                                                tooltip=tooltip1))

            location.add_child(folium.Marker(location=departure_Airports.location, tooltip="Your Address", 
                                            icon=folium.Icon(icon="f267", prefix="fa")))
            
            location.add_child(folium.Marker(location=arrival_Airports.location, tooltip="Your Destination", 
                                            icon=folium.Icon(icon="f267", prefix="fa")))

            folium.Circle(departure_Airports.location, radius=departure_Airports.radius*1000, color="green", weight=2, fill=True).add_to(mappy)
            folium.Circle(arrival_Airports.location, radius=arrival_Airports.radius*1000, color="red", weight=2, fill=True).add_to(mappy)
            mappy.add_child(fga)
            mappy.add_child(location)

            mappy.add_child(folium.LayerControl())

            mappy.save("map.html")

            self.map = mappy

        elif departure_Airports != None and departure_Airports.location != None:

            zoom = calc_zoom(departure_Airports.radius)
            figure = folium.Figure(width=1000,height=500)
            mappy = folium.Map(location = departure_Airports.location, tiles="Stamen Terrain", 
                            zoom_start=zoom, min_zoom=2).add_to(figure)

            fga = folium.FeatureGroup(name="Airports")
            location = folium.FeatureGroup(name="Your Location")

            for latitude, longitude, name, city, country in zip(departure_Airports.database["Latitude"],departure_Airports.database["Longitude"],departure_Airports.database["Airport"],
                                                                departure_Airports.database["City"],departure_Airports.database["Country"]):

                if isinstance(city, float):
                    city = "None"
                else:
                    pass

                if isinstance(name, float):
                    city = "None"
                else:
                    pass

                if isinstance(country, float):
                    city = "None"
                else:
                    pass

                tooltip1 = "Airport: "+ name + "  City: " + city + "  Country: " + country

                fga.add_child(folium.CircleMarker(location=[latitude,longitude], radius=4,
                                                tooltip=tooltip1))

            location.add_child(folium.Marker(location=departure_Airports.location, tooltip="Your Address", 
                                            icon=folium.Icon(icon="f267", prefix="fa")))

            folium.Circle(departure_Airports.location, radius=departure_Airports.radius*1000, color="green", weight=2, fill=True).add_to(mappy)
            mappy.add_child(fga)
            mappy.add_child(location)

            mappy.add_child(folium.LayerControl())

            mappy.save("map.html")
            self.map = mappy
            

        else:
            print("No Such Address")

#Used to find the right zoom for the map based on selected radius
def calc_zoom(radius):
    zooms = [27.5*(2**num) for num in range(0,10)]
    for zoom in zooms:
        if radius > 12000:
            return 0
        
        elif radius<zoom+(zoom/4):
            return 11-zooms.index(zoom)
        else:
            pass

In [3]:
import pandas as pd
import folium
from geopy import ArcGIS, distance

columns = ["ID", "Airport", "City", "Country", "IATA","ICAO", "Latitude", "Longitude", "Altitude", "Timezone", "DST", "TZ Database", "Type", "Source"]

df = pd.read_csv("airports.csv", header=None, usecols=[0,1,2,3,6,7,8])

df.columns = ["ID", "Airport", "City", "Country", "Latitude", "Longitude", "Altitude"]
df.set_index("ID", inplace=True)
df["Coordinates"] = df.apply(lambda x: (x["Latitude"],x["Longitude"]), axis=1)


address = "122 Buckingham Ave, Toronto"

df1 = pd.DataFrame([[address]])

address_coords = df1[0].apply(ArcGIS().geocode)[0].point[0:2]

df["<xks"] = df.apply(lambda x: within_x_kms(x["Coordinates"], address_coords, 30), axis=1)

df[df["<xks"]]

,Airport,City,Country,Latitude,Longitude,Altitude,Coordinates,<xks
ID,,,,,,,,
82,Buttonville Municipal Airport,Toronto,Canada,43.862202,-79.370003,650,"(43.86220169067383, -79.37000274658203)",True
144,Billy Bishop Toronto City Centre Airport,Toronto,Canada,43.627499,-79.396202,252,"(43.627499, -79.396202)",True
193,Lester B. Pearson International Airport,Toronto,Canada,43.677200,-79.630600,569,"(43.6772003174, -79.63059997559999)",True
194,Downsview Airport,Toronto,Canada,43.742500,-79.465599,652,"(43.74250030517578, -79.4655990600586)",True
9238,Markham Airport,Markham,Canada,43.935799,-79.262199,807,"(43.93579864501953, -79.26219940185547)",True

In [4]:
import folium
icon = folium.Icon(icon="plane",prefix="fa")

In [94]:
figure1 = folium.Figure(width=1000,height=500)
map1 = folium.Map(location=address_coords, tiles="Stamen Terrain", 
                   zoom_start=zoom_start, min_zoom=2).add_to(figure1)

mappy.add_child(folium.LayerControl())

map1

In [19]:
import pandas as pd
import folium
from geopy import ArcGIS, distance

#From an Address creates Object containing coordinates of Address, 
#specified radius around address in kms,
#and database with info on all airports within that radius
class Airports():
    def __init__(self, location, radius, airport_database):
        if pd.DataFrame([[location]])[0].apply(ArcGIS().geocode)[0] != None:
            self.location = pd.DataFrame([[location]])[0].apply(ArcGIS().geocode)[0].point[0:2]
            self.radius = radius
            airport_database["<xks"] = airport_database.apply(lambda x: within_x_kms(x["Coordinates"], self.location, radius), axis=1)
            self.database = airport_database[airport_database["<xks"]]
        
        else:
            self.location = None
        
def within_x_kms(p1,p2, x):
    return distance.distance(p1,p2) < x

In [16]:
figure = folium.Figure(width=1000,height=500)


midpoint = (14.7617, -17.1918)
distance = 1000000000
zoom = calc_zoom(distance)
            
mappy = folium.Map(location = midpoint, tiles="Stamen Terrain", 
                    zoom_start=zoom, min_zoom=2).add_to(figure)

mappy

In [17]:

def calc_zoom(radius):
    zooms = [27.5*(2**num) for num in range(0,10)]
    for zoom in zooms:
        if radius > 12000:
            return 0
        
        elif radius<zoom+(zoom/4):
            return 10-zooms.index(zoom)
        else:
            pass

In [106]:
df = pd.read_csv("airports.csv", header=None, usecols=[0,1,2,3,4,5,6,7])

df.columns = ["ID", "Airport", "City", "Country","IATA","ICAO", "Latitude", "Longitude"]

df["Coordinates"] = df.apply(lambda x: (x["Latitude"],x["Longitude"]), axis=1)

address1 = "52 Heydon Park Rd, Toront"
address2 = "Montreal"
kms = 50

zooms = [27.5*(2**num) for num in range(0,7)]
for zoom in zooms:
    if kms<zoom+(zoom/4):
        zoom_start = 10-zooms.index(zoom)
        break
    else:
        pass

dAirports = Airports(address1, kms, df)
aAirports = Airports(address2,kms,df)

df_routes = pd.read_csv("routes.csv")

class Routes():
    def __init__(self, departure_Airports, arrival_Airports, routes_dataframe):
        self.dLocation = departure_Airports.location
        self.aLocation = arrival_Airports.location
        df_routes["Source airport ID"] = df_routes["Source airport ID"].apply(lambda x: convert_to_int(x))
        df_routes["Destination airport ID"] = df_routes["Destination airport ID"].apply(lambda x: convert_to_int(x))
        routes_dataframe.loc[:,"Flyout"] = routes_dataframe["Source airport ID"].isin(departure_Airports.database["ID"])
        helpdataframe = routes_dataframe[routes_dataframe["Flyout"]]
        helpdataframe.loc[:,"Flyin"] = helpdataframe["Destination airport ID"].isin(arrival_Airports.database["ID"])
        self.dataframe = helpdataframe[helpdataframe["Flyin"]]
        
        helper = departure_Airports.database[departure_Airports.database["ID"].isin(self.dataframe["Source airport ID"])]
        
        
        self.dataframe["Departure Coordinates"] = helper["Coordinates"]
        
        print(helper["Coordinates"])
        #self.dataframe = self.dataframe[self.dataframe["Flyin"]]
     
def convert_to_int(x):
    if x!=r"\N":
        return int(x)
    else:
        return 0
routes = Routes(dAirports,aAirports,df_routes)
routes.dataframe

142                (43.627499, -79.396202)
191    (43.6772003174, -79.63059997559999)
Name: Coordinates, dtype: object

<ipython-input-106-3c9b1324bca2>:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.dataframe["Departure Coordinates"] = helper["Coordinates"]

,Airline,Airline ID,Source airport,Source airport ID,Destination airport,Destination airport ID,Codeshare,Stops,Equipment,Flyout,Flyin,Departure Coordinates
8189,AC,330,YTZ,144,YUL,146,Y,0,DH4,True,True,NaN
8492,AC,330,YYZ,193,YUL,146,NaN,0,319 321 320 E90 333 763 E75,True,True,NaN
36983,KL,3090,YYZ,193,YUL,146,Y,0,73W,True,True,NaN
38868,LH,3320,YYZ,193,YUL,146,Y,0,333,True,True,NaN
39731,LX,4559,YYZ,193,YUL,146,Y,0,333,True,True,NaN
45636,PD,4021,YTZ,144,YUL,146,NaN,0,DH4,True,True,NaN
54052,TS,1317,YYZ,193,YUL,146,NaN,0,310,True,True,NaN
57925,UA,5209,YYZ,193,YUL,146,Y,0,333,True,True,NaN
64900,WS,5416,YYZ,193,YUL,146,NaN,0,73W 736,True,True,NaN

In [37]:
df_routes = pd.read_csv("routes.csv")

In [99]:
import pandas
df1 = pd.DataFrame({'col': ['x', 'b', 'c','a'],"col1":["e","f","g","h"],"col2":["i","j","k","l"]})
df2 = pd.DataFrame({"col4": ["a","e","fx"]})
df1["Bool"]= df1["col"].isin(df2["col4"])
df3 = df1[df1["Bool"]]
df1

  col col1 col2   Bool
0   x    e    i  False
1   b    f    j  False
2   c    g    k  False
3   a    h    l   True

In [23]:
helper = departure_Airports.database[departure_Airports["ID"].isin(self.routedataframe["Source Airport ID"])]
helper

NameError: name 'departure_Airports' is not defined

In [63]:
import geographiclib as glib
flattening = 1/298.257223563
equ_rad = 6371000

earth = glib.geodesic.Geodesic(equ_rad,flattening)
geo_line = earth.InverseLine(43.6772003174, -79.63059997559999, 48.353802, 11.7861)

def get_point(dist):
    lat = geo_line.Position(dist)["lat2"]
    lon = geo_line.Position(dist)["lon2"]
    return (lat,lon)

r = range(0, round(geo_line.s13), 10000)
arcline_list = []
for i in r:
    arcline_list.append(get_point(i))
arcline_list.append(get_point(geo_line.s13))